# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad924fbdfd92a50896abe84725970153586067d10dd650e23688a903f1838f6ab6e59f812f0ac123d976dbecfd35975e18340c007941dd8804941f47e089b4f

test:
  secret_key_base: 9d4662c60990463911fb9598d17f3ecd464bf5fb997bc7b94331f08c5f73680da5399b3c28315424e968c6c0b8bcd9ad7e821f380449d76869bfb90d19257d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
